name: Automação QA - Execução e Relatório

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  testar-e-gerar-relatorio:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v4

      - name: ☕ Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: 🚀 Executar Testes (Maven)
        run: mvn clean test cluecumber-report:reporting

      - name: ⚙️ Setup do GitHub Pages
        uses: actions/configure-pages@v5
        if: always()

      - name: 📦 Fazer Upload do Relatório Cluecumber
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          path: target/cluecumber-report

  deploy-pages:
    needs: testar-e-gerar-relatorio
    runs-on: ubuntu-latest
    if: always()

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 🌐 Deploy para o GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4